### ISSUE TITLE
Doing streaming for response to handle UX long responses

### ISSUE THREAD

**Issue by fadingNA** [AryanK1511/github-echo#40]
https://github.com/AryanK1511/github-echo/blob/d300403d9792c600538ced63282a11792012b134/application/core/gemini_model.py#L42

enable streaming=True, might be a better user experience for waiting Gemini generate the prompt instead of wait to stdout the answer in one time.

https://github.com/google-gemini/cookbook/blob/main/quickstarts/Streaming.ipynb

**Comment by AryanK1511** [comment]
Hello @fadingNA !

Thank you so much for your thoughtful suggestion! I’ve implemented a spinner in #43, and it’s working great. I am very satisfied the user experience for now .

I really appreciate your input but for now, I don’t plan to implement streaming data since the responses we're handling aren’t large enough to warrant it. But your suggestion has definitely given me some valuable insights for future improvements!

Your feedback is truly appreciated!
